language: cpp
compiler: gcc
sudo: require
dist: trusty

env:
  global:  
   - GTEST_DIR=${TRAVIS_BUILD_DIR}/gtest

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages: &native_deps
    - cmake
    - libusb-1.0-0-dev
    - libfftw3-dev
    - libgtest-dev
    - gcc-5
    - g++-5

# We are testing
# * linux with g++5 (and clang 3.6)
# * osx with clang 3.6
matrix:
  include:
    - compiler: gcc
      env: CMAKE_CXX_COMPILER=g++-5
      os: linux
    - compiler: clang
      env: CMAKE_CXX_COMPILER=/usr/bin/clang++
      os: osx
  
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install libusb fftw qt5; export CMAKE_PREFIX_PATH=$(brew --prefix qt5); fi
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo add-apt-repository -y ppa:beineri/opt-qt542-trusty;sudo apt-get -qq update; sudo apt-get --yes install -qq qt54base; QTDIR="/opt/qt55"; PATH="$QTDIR/bin:$PATH"; source /opt/qt54/bin/qt54-env.sh; fi

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ../
 
script:
    - make DESTDIR=appdir -j$(nproc) install ; find appdir/
    - mkdir -p appdir/usr/share/applications/ ; cp ../openhantek.desktop appdir/usr/share/applications/ # FIXME, "make install" should do that
    - mkdir -p appdir/usr/share/icons/hicolor/scalable/ ; cp ../openhantek/res/images/openhantek.svg appdir/usr/share/icons/hicolor/scalable/ # FIXME, "make install" should do that
    - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
    - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
    - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
    - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
    - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
    - # Workaround to increase compatibility with older systems; see https://github.com/darealshinji/AppImageKit-checkrt for details
    - mkdir -p appdir/usr/optional/ ; wget -c https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/exec-x86_64.so -O ./appdir/usr/optional/exec.so
    - rm -f appdir/AppRun ; cp ../AppRun appdir/ ; chmod +x appdir/AppRun
    - mkdir -p appdir/usr/optional/libstdc++/ ; cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 ./appdir/usr/optional/libstdc++/
    - ( cd appdir ; wget -c https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/AppRun-patched-x86_64 -O AppRun2 ; chmod a+x AppRun2)
    - ./linuxdeployqt*.AppImage --appimage-extract
    - export PATH=$(readlink -f ./squashfs-root/usr/bin):$PATH
    - ./squashfs-root/usr/bin/appimagetool -g ./appdir/ "OpenHantek-$VERSION-x86_64.AppImage"
    -  curl --upload-file OpenHantek-*-x86_64.AppImage https://transfer.sh/
    
before_deploy:
    - sudo make package

notifications:
  on_success: change
  on_failure: always

# User "ci-openhantek". Uses a travis encrypted github access token for that user.
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: XGiTAo3bIZXq1gWQQaodllxTX/Wg0Jwgs0Dxtwi688usIlyUheMmmda9Ot9hdrXTlxJJICgUE1RVwjYynE7c7uUKE9E82QlM/E05m+rAYXzCCzOdrkku2C7netAnFs8ZbNlfMn459QOAkPvbF0Wfx1h+pAYxpXbTFl0cwatBxIjVxc4BUpulbY2SJK413mm8nOwfHI/MpBaJwX2A1vaV4IevXWPVnLrypqA2g7B4N9NHnLB/kuBo6nKM9sjOLfvV7Lzmq/S2a9GeDF8JOO3OPjiQVLV+fwQbUn8l4Rfm6vzs1h4MYJ0E7QBV+laLbD3tHic9IcOHReinG64OTiA4uL8W75V556qGme4Eb6TId2SwnNtJPRU5zn5KIB3J6qXSrqA0XiPjm+lyxQF/LB4hIgMtr2r0t3a2+6zSOuu55D4W+IF4S7Q2ogRKyuu9Ku/QXPcmYRZQNkieXNUn7D6dANyQb6ml4uREZPlwHqLnbOi5RMBi5awiYY6NI8DLdcO4NXn+IsaWbJS50GQRGWJs/hB4PWXeuSAkjQ0kenPOf3ZcDhf73ynb/H6Z2gormgAFM91VC8yhvnjm+2zUMm+ChtYzX7xytCt34Itsrv7U+U1OdECMXRZkbbbvebbTeuo2jBqMdKEp4cDCvPEdrXlWwAFL//3sQvf2O23QEFkpTxY=
  file: "packages/*"
  on:
    repo: OpenHantek/openhantek
    tags: true
